[build]
builder = "nixpacks"

[deploy]
startCommand = "magg serve --http --host 0.0.0.0 --port ${PORT:-8000}"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[services.variables]
MAGG_LOG_LEVEL = "INFO"
MAGG_CONFIG_PATH = "/app/.magg/config.json"
MAGG_READ_ONLY = "false"
MAGG_AUTO_RELOAD = "true"
MAGG_HOST = "0.0.0.0"
MAGG_SELF_PREFIX = "magg"
MAGG_PREFIX_SEP = "_"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
