[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[services.variables]
MAGG_LOG_LEVEL = "INFO"
MAGG_CONFIG_PATH = "/home/magg/.magg/config.json"
MAGG_READ_ONLY = "false"
MAGG_AUTO_RELOAD = "true"
MAGG_HOST = "0.0.0.0"
MAGG_SELF_PREFIX = "magg"
MAGG_PREFIX_SEP = "_"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
